/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_management;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane; 
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


/**
 *
 * @author manojkulkarni
 */
public class create_user extends javax.swing.JFrame implements ActionListener{

    

    /**
     * Creates new form RegistrationForm
     */
    JTextFieldDateEditor dteditor;
    public create_user() {
        initComponents();
        initDateEditor();
        setTitle("Registration Form"); 
        setDefaultCloseOperation(EXIT_ON_CLOSE); 
    
    }

    public void actionPerformed(ActionEvent e) 
    { 
      
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        mob = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        occupation = new javax.swing.JLabel();
        qualification = new javax.swing.JLabel();
        pan = new javax.swing.JLabel();
        aadhar = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tmname = new javax.swing.JTextField();
        tsname = new javax.swing.JTextField();
        tmob = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tsalary = new javax.swing.JTextField();
        tpan = new javax.swing.JTextField();
        taadhar = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        pwd = new javax.swing.JLabel();
        retypepwd = new javax.swing.JLabel();
        tpwd = new javax.swing.JPasswordField();
        tretypepwd = new javax.swing.JPasswordField();
        reset = new javax.swing.JButton();
        tsex = new javax.swing.JComboBox<String>();
        term = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadd = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        checked_savings = new javax.swing.JCheckBox();
        checked_current = new javax.swing.JCheckBox();
        qualification_options = new javax.swing.JComboBox();
        occupation_options = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fname.setText("First Name");

        mname.setText("Middle Name");

        sname.setText("Last Name");

        mob.setText("Mobile No");

        sex.setText("Sex");

        dob.setText("DOB");

        email.setText("Email ID");

        add.setText("Address");

        salary.setText("Salary");

        occupation.setText("Occupation");

        qualification.setText("Qualification");

        pan.setText("PAN No");

        aadhar.setText("Aadhar No");

        temail.setPreferredSize(new java.awt.Dimension(6, 30));

        tsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsalaryActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        pwd.setText("Password");

        retypepwd.setText("Retype Password");

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        tsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Other" }));
        tsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsexActionPerformed(evt);
            }
        });

        term.setText("Accept Terms and Conditions");
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });

        tadd.setColumns(20);
        tadd.setRows(5);
        tadd.setMaximumSize(new java.awt.Dimension(164, 88));
        tadd.setMinimumSize(getPreferredSize());
        tadd.setPreferredSize(new java.awt.Dimension(164, 88));
        jScrollPane1.setViewportView(tadd);

        jLabel2.setText("Type of account(s)");

        checked_savings.setText("Savings");
        checked_savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checked_savingsActionPerformed(evt);
            }
        });

        checked_current.setText("Current");
        checked_current.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checked_currentActionPerformed(evt);
            }
        });

        qualification_options.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option", "Non Graduate", "Graduate", "Post Graduate", "Others" }));

        occupation_options.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Option", "Business", "Service", "Retired", "Others" }));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 0, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management/ibank2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION FORM");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mname)
                            .addComponent(fname)
                            .addComponent(sname)
                            .addComponent(mob)
                            .addComponent(sex)
                            .addComponent(dob)
                            .addComponent(email)
                            .addComponent(add)
                            .addComponent(salary))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tmname, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tsname, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tmob, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tsex, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupation)
                            .addComponent(qualification)
                            .addComponent(pan)
                            .addComponent(aadhar)
                            .addComponent(pwd)
                            .addComponent(retypepwd)
                            .addComponent(reset)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(term)
                                    .addComponent(submit)
                                    .addComponent(tpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taadhar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tpwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(checked_savings)
                                            .addGap(18, 18, 18)
                                            .addComponent(checked_current))
                                        .addComponent(tretypepwd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(qualification_options, 0, 166, Short.MAX_VALUE)
                                        .addComponent(occupation_options, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mname))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sname)
                    .addComponent(tsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mob)
                    .addComponent(tmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sex)
                    .addComponent(tsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dob)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salary)
                            .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(occupation)
                            .addComponent(occupation_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qualification)
                            .addComponent(qualification_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pan)
                            .addComponent(tpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aadhar)
                            .addComponent(taadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwd)
                            .addComponent(tpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retypepwd)
                            .addComponent(tretypepwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checked_savings)
                                    .addComponent(checked_current))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(term)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reset)
                                    .addComponent(submit))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked

        if((checked_savings.isSelected() || checked_current.isSelected())==false | tfname.getText().isEmpty() | tmname.getText().isEmpty() |tsname.getText().isEmpty() |tadd.getText().isEmpty() |tmob.getText().isEmpty() |temail.getText().isEmpty() | occupation_options.getSelectedIndex()==0 |tsalary.getText().isEmpty() | qualification_options.getSelectedIndex()==0 |tpan.getText().isEmpty() | taadhar.getText().isEmpty()){
        JPanel msg = new JPanel();
        JOptionPane.showMessageDialog(msg, "Please Fill all the Fields!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int proceed=1;
            //Aadhar number should be 12 digits long.
            if(String.valueOf(taadhar.getText()).length()!=12){
                JOptionPane.showMessageDialog(create_user.this, "Aadhar number is not 12 digits long. Please renter.");
                taadhar.setText("");
                proceed=0;
            }
            //Mobile number should be 10 digits long.
            if(String.valueOf(tmob.getText()).length()!=10){
                JOptionPane.showMessageDialog(create_user.this, "Mobile number is not 10 digits long. Please renter.");
                tmob.setText("");
                proceed=0;
            }
            //Email should contain the symbol '@'.
            if(!String.valueOf(temail.getText()).contains("@")){
                JOptionPane.showMessageDialog(create_user.this, "Please check email id and enter again.");
                temail.setText("");
                proceed=0;
            }
            if(String.valueOf(tfname.getText()).contains("1")||String.valueOf(tfname.getText()).contains("2")||String.valueOf(tfname.getText()).contains("3")||String.valueOf(tfname.getText()).contains("4")||String.valueOf(tfname.getText()).contains("5")||String.valueOf(tfname.getText()).contains("6")||String.valueOf(tfname.getText()).contains("7")||String.valueOf(tfname.getText()).contains("8")||String.valueOf(tfname.getText()).contains("9")||String.valueOf(tfname.getText()).contains("0")){
                JOptionPane.showMessageDialog(create_user.this, "Please check first name and enter again.");
                tfname.setText("");
                proceed=0;
            }
             if(String.valueOf(tmname.getText()).contains("1")||String.valueOf(tmname.getText()).contains("2")||String.valueOf(tmname.getText()).contains("3")||String.valueOf(tmname.getText()).contains("4")||String.valueOf(tmname.getText()).contains("5")||String.valueOf(tmname.getText()).contains("6")||String.valueOf(tmname.getText()).contains("7")||String.valueOf(tmname.getText()).contains("8")||String.valueOf(tmname.getText()).contains("9")||String.valueOf(tmname.getText()).contains("0")){
                JOptionPane.showMessageDialog(create_user.this, "Please check middle name and enter again.");
                tmname.setText("");
                proceed=0;
            } if(String.valueOf(tsname.getText()).contains("1")||String.valueOf(tsname.getText()).contains("2")||String.valueOf(tsname.getText()).contains("3")||String.valueOf(tsname.getText()).contains("4")||String.valueOf(tsname.getText()).contains("5")||String.valueOf(tsname.getText()).contains("6")||String.valueOf(tsname.getText()).contains("7")||String.valueOf(tsname.getText()).contains("8")||String.valueOf(tsname.getText()).contains("9")||String.valueOf(tsname.getText()).contains("0")){
                JOptionPane.showMessageDialog(create_user.this, "Please check last name and enter again.");
                tsname.setText("");
                proceed=0;
            }
            if(String.valueOf(tpan.getText()).length()!=8){
                JOptionPane.showMessageDialog(create_user.this, "PAN number is not 10 digits long. Please renter.");
                tpan.setText("");
                proceed=0;
            }
            if(proceed==1){
                int option = JOptionPane.showConfirmDialog(null, "Do you want to submit the form?", "Submit Form", JOptionPane.YES_NO_OPTION);
        if(option == 0){
            System.out.println("Form data accessed.");
            if (term.isSelected()) {
                int preference=0;
                if(checked_current.isSelected()==false && checked_savings.isSelected()==true){
                    preference=0;
                }
                else if(checked_current.isSelected()==true && checked_savings.isSelected()==false){
                    preference=1;
                }
                else if(checked_current.isSelected()==true && checked_savings.isSelected()==true){
                    preference=2;
                }
                String first_name = tfname.getText();
                String middle_name = tmname.getText();
                String last_name = tsname.getText();
                String sex=String.valueOf(tsex.getSelectedItem());
                String mobile_number = tmob.getText();
                //String day= String.valueOf(tdate.getSelectedItem());
                //String month=String.valueOf(tmonth.getSelectedItem());
                //String year=String.valueOf(tyear.getSelectedItem());
                //String date=year+"-"+month+"-"+day;
                
                DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
                String date = df.format(jDateChooser1.getDate());
                
                System.out.println(date);
                String email = temail.getText();
                String address = tadd.getText();
                int salary = Integer.parseInt(tsalary.getText());
                
                String occupation = String.valueOf(occupation_options.getSelectedItem());
                String qualification = String.valueOf(qualification_options.getSelectedItem());
                String pan_card = String.valueOf(tpan.getText());
                String aadhar = String.valueOf(taadhar.getText());
                
                String password = tpwd.getText();
                String retype_password = tretypepwd.getText();
                if(!retype_password.equals(password))
                {
                    JOptionPane.showMessageDialog(null, "Password Does Not Match, Retype the password");
                    tpwd.setText("");
                    tretypepwd.setText("");
                }
                try{
                    /*Establish connect with the database*/
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                    Statement st=(Statement) conn.createStatement();
                    st.executeUpdate("INSERT INTO customer (customer_password,c_fn,c_mn,c_ln,c_mob,c_sex,c_dob,c_email_id,c_address,c_salary,c_occupation,c_qualification,c_IT_PAN,c_aadhar_no,verified,pref) VALUES ('"+password+"','"+first_name+"','"+middle_name+"','"+last_name+"','"+mobile_number+"','"+sex+"','"+date+"','"+email+"','"+address+"','"+salary+"','"+occupation+"','"+qualification+"','"+pan_card+"','"+aadhar+"','no','"+preference+"')");
                    JOptionPane.showMessageDialog(null, "Form Submitted Successfully!", "Confirm Submission", JOptionPane.PLAIN_MESSAGE);
                    checked_savings.setSelected(false);checked_current.setSelected(false);
                    System.exit(0);
                }catch(Exception e){
                    System.out.println(e);
                    System.out.println("Error in connecting to the database or execting the update.");
                }
            } 
            else {
                 JOptionPane.showMessageDialog(null, 
                              "Please accept the Terms and Conditions", 
                              "Confirm Submission", 
                              JOptionPane.PLAIN_MESSAGE);   
                    }        
        } 
       else{
           
        }
        
       }  
    }
        
        
        
        
          
    }//GEN-LAST:event_submitMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void tsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsexActionPerformed
        JComboBox s = (JComboBox)evt.getSource();
            String smsg = (String)s.getSelectedItem();
// TODO add your handling code here:
    }//GEN-LAST:event_tsexActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        String def = ""; 
            tfname.setText(def); 
            tmname.setText(def);
            tsname.setText(def);
          
            tadd.setText(def); 
            tmob.setText(def); 
            temail.setText(def); 
            occupation_options.setSelectedIndex(0);
            tsalary.setText(def);
            qualification_options.setSelectedIndex(0);
            tpan.setText(def);
            taadhar.setText(def);
            term.setSelected(false); 
            //tdate.setSelectedIndex(0); 
            //tmonth.setSelectedIndex(0); 
            //tyear.setSelectedIndex(0); 
            tpwd.setText(def);
            tretypepwd.setText(def);
// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        
    }//GEN-LAST:event_resetMouseClicked

    private void tsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsalaryActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termActionPerformed

    private void checked_savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checked_savingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checked_savingsActionPerformed

    private void checked_currentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checked_currentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checked_currentActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        first_page prev_form=new first_page();
        prev_form.getContentPane().setBackground(new java.awt.Color(0, 221, 229));
        prev_form.setVisible(true);
        //Closing the original windows.
        JComponent comp2 = (JComponent) evt.getSource();
        Window win=SwingUtilities.getWindowAncestor(comp2);
        win.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_user().setVisible(true);
            }
        });
    }

    private void setLocationRelativeto(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private void initDateEditor(){
        dteditor= (JTextFieldDateEditor) jDateChooser1.getDateEditor();
        dteditor.setEditable(false);
        dteditor.setBackground(Color.white);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadhar;
    private javax.swing.JLabel add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JCheckBox checked_current;
    private javax.swing.JCheckBox checked_savings;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fname;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel mob;
    private javax.swing.JLabel occupation;
    private javax.swing.JComboBox occupation_options;
    private javax.swing.JLabel pan;
    private javax.swing.JLabel pwd;
    private javax.swing.JLabel qualification;
    private javax.swing.JComboBox qualification_options;
    private javax.swing.JButton reset;
    private javax.swing.JLabel retypepwd;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel sname;
    private javax.swing.JButton submit;
    private javax.swing.JTextField taadhar;
    private javax.swing.JTextArea tadd;
    private javax.swing.JTextField temail;
    private javax.swing.JCheckBox term;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tmname;
    private javax.swing.JTextField tmob;
    private javax.swing.JTextField tpan;
    private javax.swing.JPasswordField tpwd;
    private javax.swing.JPasswordField tretypepwd;
    private javax.swing.JTextField tsalary;
    private javax.swing.JComboBox<String> tsex;
    private javax.swing.JTextField tsname;
    // End of variables declaration//GEN-END:variables

    private boolean checkEmpty() {
        
        
        //term.setSelected(false); 
//            tdate.getSelectedIndex(0); 
//            tmonth.setSelectedIndex(0); 
//            tyear.setSelectedIndex(0);)
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           
    }
}

   

    

