/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_management;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Window;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mohammad Anas
 */
public class fund_transfer extends javax.swing.JFrame {
    
    /**
     * Creates new form fund_transfer
     */
    
    //Initialising the variables for locating the account.
    int user_id;
    String password;
    int user_id_acc;
    public fund_transfer(int user_id, String password) {
        initComponents();
        this.user_id=user_id;
        this.password=password;
        /***
         IMPORTANT: Using the constructor is the only way to modify
         *          behaviour of buttons etc before window is opened.
         *          Run method cannot be used.
         ***/
        jComboBox1.setSelectedItem("--NULL--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showbalance = new javax.swing.JLabel();
        displaybalance = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bank_management/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("fund_transfer.jLabel1.text_1")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText(bundle.getString("fund_transfer.jLabel2.text_1")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText(bundle.getString("fund_transfer.jLabel4.text_1")); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--NULL--", "Savings Account", "Current Account" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField1.setText(bundle.getString("fund_transfer.jTextField1.text_1")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField2.setText(bundle.getString("fund_transfer.jTextField2.text_1")); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTextField3.setText(bundle.getString("fund_transfer.jTextField3.text_1")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText(bundle.getString("fund_transfer.jLabel5.text")); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText(bundle.getString("fund_transfer.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showbalance.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        showbalance.setText(bundle.getString("fund_transfer.showbalance.text_1")); // NOI18N

        displaybalance.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        displaybalance.setText(bundle.getString("fund_transfer.displaybalance.text_1")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management/ibank2.png"))); // NOI18N
        jLabel3.setText(bundle.getString("fund_transfer.jLabel3.text_1")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText(bundle.getString("fund_transfer.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(113, 113, 113)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(236, 236, 236)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showbalance)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displaybalance, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displaybalance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showbalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("--NULL--")){
            //Hide the textfields to prevent user for entering information.
            jButton1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            showbalance.setVisible(false);
            displaybalance.setVisible(false);
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
        }
        if(jComboBox1.getSelectedItem().equals("Savings Account")){
            try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                
                //Fetch the account number using the user_id from accounts table.
                ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                int flag=0;
                int balance=0;
                while(rs.next()){
                    if(rs.getInt("customer_id")==user_id && rs.getString("acc_type").equals("SAVINGS")){
                        flag=1;
                        user_id_acc=rs.getInt("acc_number");
                        //Storing the balance
                        balance=rs.getInt("balance");
                        System.out.println("Balance stored: "+ balance);
                        displaybalance.setText(String.valueOf(balance));
                        break;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(fund_transfer.this,"This customer id doesnt have savings account.Please select different option");
                    //Hide the textfields to prevent user for entering information.
                    jButton1.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                    showbalance.setVisible(false);
                    displaybalance.setVisible(false);
                    jTextField1.setVisible(false);
                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                }
                else if(flag==1){
                jButton1.setVisible(true);
                jLabel2.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                showbalance.setVisible(true);
                displaybalance.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                }
                
            }catch(Exception e){
                System.out.println("Error in Savings connection.");
            }
            
        }
        if(jComboBox1.getSelectedItem().equals("Current Account")){
           try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                
                //Fetch the account number using the user_id from accounts table.
                ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                int flag=0;
                int balance=0;
                while(rs.next()){
                    if(rs.getInt("customer_id")==user_id && rs.getString("acc_type").equals("CURRENT")){
                        flag=1;
                        user_id_acc=rs.getInt("acc_number");
                        //Storing the balance
                        balance=rs.getInt("balance");
                        System.out.println("Balance stored: "+ balance);
                        displaybalance.setText(String.valueOf(balance));
                        break;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(fund_transfer.this,"This customer id doesnt have current account.Please select different option");
                    //Hide the textfields to prevent user for entering information.
                    jButton1.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                    showbalance.setVisible(false);
                    displaybalance.setVisible(false);
                    jTextField1.setVisible(false);
                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                }
                else if(flag==1){
                    jButton1.setVisible(true);
                    jLabel2.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    showbalance.setVisible(true);
                    displaybalance.setVisible(true);
                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
             
                }
                
            }catch(Exception e){
                System.out.println("Error in Cuurent connection.");
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
        if(jComboBox1.getSelectedItem().equals("Savings Account")){
            try{
                //System.out.println("Check 0");
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                int transfer=Integer.parseInt(jTextField1.getText());
                if(transfer>Integer.parseInt(displaybalance.getText())){
                    JOptionPane.showMessageDialog(fund_transfer.this,"Amount cannot exceed available balance.");
                    jTextField1.setText(null);jTextField1.grabFocus();
                }
                else if(transfer<=0){
                    JOptionPane.showMessageDialog(fund_transfer.this,"Amount cannot be 0 or negative.");
                }
                else
                {
                    String remark=jTextField2.getText();
                    int receiving_acc=Integer.parseInt(jTextField3.getText());
                    System.out.println("Receiving acc number: "+receiving_acc);
                    ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                    int flag=0;
                    int balance_of_receiver=0;
                    while(rs.next()){
                        if(rs.getInt("acc_number")==receiving_acc){
                            flag=1;
                            balance_of_receiver=rs.getInt("balance");
                            break;
                        }
                    }
                    if(flag==0){
                        JOptionPane.showMessageDialog(fund_transfer.this,"Receiving account number doesnt exist.");
                    }
                    else if(flag==1){
                        int subtract=(Integer.parseInt(displaybalance.getText()))-transfer;
                        int add=balance_of_receiver+transfer;
                        //Updating the accounts.
                        st.executeUpdate("UPDATE accounts SET balance="+subtract+" WHERE acc_number="+user_id_acc);
                        st.executeUpdate("UPDATE accounts SET balance="+add+" WHERE acc_number="+receiving_acc);
                        //Inserting the values in tramsaction table.
                        st.executeUpdate("INSERT INTO transaction(acc_number,remark,type_of_transfer,from_to,amount,cheque_number,deposit_withdraw) VALUES ('"+user_id_acc+"','"+remark+"','fund transfer','"+receiving_acc+"','"+transfer+"','-1','withdraw') ");
                        st.executeUpdate("INSERT INTO transaction(acc_number,remark,type_of_transfer,from_to,amount,cheque_number,deposit_withdraw) VALUES ('"+receiving_acc+"','"+remark+"','fund transfer','"+user_id_acc+"','"+transfer+"','-1','deposit') ");
                       JOptionPane.showMessageDialog(fund_transfer.this,"Transaction successful!");
                       jComboBox1.setSelectedIndex(0);
                    }
                }
            }catch(Exception e){
                System.out.println(e);
                System.out.println("Error in confirming transaction.");
            }
        }
        else if(jComboBox1.getSelectedItem().equals("Current Account")){
            try{
                //System.out.println("Check 0");
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                int transfer=Integer.parseInt(jTextField1.getText());
                if(transfer>Integer.parseInt(displaybalance.getText())){
                    JOptionPane.showMessageDialog(fund_transfer.this,"Amount cannot exceed available balance.");
                }
                else if(transfer<=0){
                    JOptionPane.showMessageDialog(fund_transfer.this,"Amount cannot be 0 or negative.");
                }
                else
                {
                    String remark=jTextField2.getText();
                    int receiving_acc=Integer.parseInt(jTextField3.getText());
                    System.out.println("Receiving acc number: "+receiving_acc);
                    ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                    //System.out.println("Check 1");
                    int flag=0;
                    int balance_of_receiver=0;
                    while(rs.next()){
                        //System.out.println("Check 1");
                        if(rs.getInt("acc_number")==receiving_acc){
                            flag=1;
                            balance_of_receiver=rs.getInt("balance");
                           // System.out.println("Check 2");
                            break;
                        }
                    }
                    if(flag==0){
                        JOptionPane.showMessageDialog(fund_transfer.this,"Receiving account number doesnt exist.");
                    }
                    else if(flag==1){
                        int subtract=(Integer.parseInt(displaybalance.getText()))-transfer;
                        int add=balance_of_receiver+transfer;
                        //Updating the balances in the accounts.
                        System.out.println("a");
                        st.executeUpdate("UPDATE accounts SET balance="+subtract+" WHERE acc_number="+user_id_acc);
                        System.out.println(user_id_acc);
                        System.out.println("a");
                        st.executeUpdate("UPDATE accounts SET balance="+add+" WHERE acc_number="+receiving_acc);
                        System.out.println("a");
                        //Enter two entries in transaction history.
                        st.executeUpdate("INSERT INTO transaction(acc_number,remark,type_of_transfer,from_to,amount,cheque_number,deposit_withdraw) VALUES ('"+user_id_acc+"','"+remark+"','fund transfer','"+receiving_acc+"','"+transfer+"','-1','withdraw') ");
                        System.out.println("a");
                        st.executeUpdate("INSERT INTO transaction(acc_number,remark,type_of_transfer,from_to,amount,cheque_number,deposit_withdraw) VALUES ('"+receiving_acc+"','"+remark+"','fund transfer','"+user_id_acc+"','"+transfer+"','-1','deposit') ");
                        JOptionPane.showMessageDialog(fund_transfer.this,"Transaction successful!");
                        jComboBox1.setSelectedIndex(0);
                    }
                }
            }catch(Exception e){
                System.out.println(e);
                System.out.println("Error in confirming transaction.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        user_login_validated prev_form=new user_login_validated(user_id, password);
        prev_form.setVisible(true);
        prev_form.getContentPane().setBackground(new java.awt.Color(0, 221, 229));
        //Closing the original windows.
        JComponent comp2 = (JComponent) evt.getSource();
        Window win=SwingUtilities.getWindowAncestor(comp2);
        win.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fund_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fund_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fund_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fund_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displaybalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel showbalance;
    // End of variables declaration//GEN-END:variables
}
