/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_management;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Window;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mohammad Anas
 */


public class transaction_history extends javax.swing.JFrame {

    class print_history implements Runnable{
        ResultSet rs;
        JTextPane textwrite;
        public print_history(ResultSet rs,JTextPane textwrite){
            this.rs=rs;
            this.textwrite=textwrite;
        }
        public void run(){
            try {
                StringBuilder sb1=new StringBuilder();
                int i=1;
                //sb1.append("               DEBIT\n");
                while(rs.next()){
                    sb1.append(i+".) Amount= "+rs.getInt("amount")+"\n    Remark = "+(rs.getString("remark"))+"\n");
                    i++;
                }
                textwrite.setText(sb1.toString());
                textwrite.setEditable(false);
            } catch (SQLException ex) {
                Logger.getLogger(transaction_history.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}
    /**
     * Creates new form transaction_history
     */
    int user_id;
    String password;
    public transaction_history(int user_id,String password) {
        initComponents();
        jComboBox1.setSelectedItem("--NULL--");
        this.user_id=user_id;
        this.password=password;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textwrite1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textwrite2 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        textwrite3 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--NULL--", "Savings Account", "Current Account" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Choose the type of account:");

        textwrite1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jScrollPane6.setViewportView(textwrite1);

        textwrite2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jScrollPane2.setViewportView(textwrite2);

        textwrite3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jScrollPane7.setViewportView(textwrite3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management/ibank2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("ACCOUNT STATEMENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("DEBIT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("CREDIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(67, 67, 67)))))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("--NULL--")){
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            textwrite1.setVisible(false);
            textwrite2.setVisible(false);
            textwrite3.setVisible(false);
            textwrite1.setEditable(true);
            textwrite2.setEditable(true);
            textwrite3.setEditable(true);
            textwrite1.setText("");
            textwrite2.setText("");
            textwrite3.setText("");
        }
        else if(jComboBox1.getSelectedItem().equals("Savings Account")){
            textwrite1.setVisible(true);
            textwrite2.setVisible(true);
            textwrite3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            try{
                /*Establish connect with the database*/
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                int flag=0;
                int acc_num=0;
                ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                while(rs.next()){
                    if(rs.getInt("customer_id")==user_id && rs.getString("acc_type").equals("SAVINGS")){
                        flag=1;
                        acc_num=rs.getInt("acc_number");
                        break;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(transaction_history.this,"The account doesnt exist. Please try again.");
                    jComboBox1.setSelectedIndex(0);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                    textwrite1.setVisible(false);
                    textwrite2.setVisible(false);
                    textwrite3.setVisible(false);
                    textwrite1.setEditable(true);
                    textwrite2.setEditable(true);
                    textwrite3.setEditable(true);
                    textwrite1.setText("");
                    textwrite2.setText("");
                    textwrite3.setText("");
                }
                else if(flag==1){
                    Thread t1=new Thread(new print_history(st.executeQuery("SELECT * FROM transaction WHERE acc_number="+acc_num+" AND deposit_withdraw="+"'withdraw'"),textwrite1));
                    t1.start();
                    //This is because if we reassign rs using same statement object then the earlier set gets overwritten.
                    Statement st2=(Statement) conn.createStatement();
                    Thread t2=new Thread(new print_history(st2.executeQuery("SELECT * FROM transaction WHERE acc_number="+acc_num+" AND deposit_withdraw="+"'deposit'"),textwrite2));
                    t2.start();
                    //This to prevent the printing of final balance interfering with the printing of credit and debit history.
                    try{
                        t1.join();
                        t2.join();
                    }catch(Exception e){
                        System.out.println("Error in joining the threads.");
                    }
                    rs=st.executeQuery("SELECT * FROM accounts WHERE acc_number="+acc_num);
                    rs.next();
                    int curr_balance=rs.getInt("balance");
                    textwrite3.setText("  Final balance= "+(curr_balance));
                    textwrite3.setEditable(false);
                }
            }catch(Exception e){
                System.out.println(e);
                System.out.println("Error in savings transactions.");
            }
        }
        else if(jComboBox1.getSelectedItem().equals("Current Account")){
            textwrite1.setVisible(true);
            textwrite2.setVisible(true);
            textwrite3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            try{
                /*Establish connect with the database*/
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
                Statement st=(Statement) conn.createStatement();
                int flag=0;
                int acc_num=0;
                ResultSet rs=st.executeQuery("SELECT * FROM accounts");
                while(rs.next()){
                    if(rs.getInt("customer_id")==user_id && rs.getString("acc_type").equals("CURRENT")){
                        flag=1;
                        acc_num=rs.getInt("acc_number");
                        break;
                    }
                }
                if(flag==0){
                    JOptionPane.showMessageDialog(transaction_history.this,"The account doesnt exist. Please try again.");
                    jComboBox1.setSelectedIndex(0);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                    textwrite1.setVisible(false);
                    textwrite2.setVisible(false);
                    textwrite3.setVisible(false);
                    textwrite1.setEditable(true);
                    textwrite2.setEditable(true);
                    textwrite3.setEditable(true);
                    textwrite1.setText("");
                    textwrite2.setText("");
                    textwrite3.setText("");
                }
                else if(flag==1){
                    Thread t1=new Thread(new print_history(st.executeQuery("SELECT * FROM transaction WHERE acc_number="+acc_num+" AND deposit_withdraw="+"'withdraw'"),textwrite1));
                    t1.start();
                    //This is because if we reassign rs using same statement object then the earlier set gets overwritten.
                    Statement st2=(Statement) conn.createStatement();
                    Thread t2=new Thread(new print_history(st2.executeQuery("SELECT * FROM transaction WHERE acc_number="+acc_num+" AND deposit_withdraw="+"'deposit'"),textwrite2));
                    t2.start();
                    //This to prevent the printing of final balance interfering with the printing of credit and debit history.
                    try{
                        t1.join();
                        t2.join();
                    }catch(Exception e){
                        System.out.println("Error in joining the threads.");
                    }
                    rs=st.executeQuery("SELECT * FROM accounts WHERE acc_number="+acc_num);
                    rs.next();
                    int curr_balance=rs.getInt("balance");
                    textwrite3.setText("  Final balance= "+(curr_balance));
                    textwrite3.setEditable(false);
                }
            }catch(Exception e){
                System.out.println(e);
                System.out.println("Error in current transactions.");
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        user_login_validated prev_form=new user_login_validated(user_id, password);
        prev_form.setVisible(true);
        prev_form.getContentPane().setBackground(new java.awt.Color(0, 221, 229));
        //Closing the original windows.
        JComponent comp2 = (JComponent) evt.getSource();
        Window win=SwingUtilities.getWindowAncestor(comp2);
        win.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new transaction_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane textwrite1;
    private javax.swing.JTextPane textwrite2;
    private javax.swing.JTextPane textwrite3;
    // End of variables declaration//GEN-END:variables
}
